import { NetworkAgent } from './NetworkAgent.js';
import { Cross, Mutate } from './evolve.js';
import { EvolvingNetwork } from '../networks.js';

class EvolvingNetworkAgent extends NetworkAgent {
    constructor(networkConfig, fitness) {
        super(new EvolvingNetwork(networkConfig));

        /*
        fitness: {
            score: 0,
            normalized: 0
        }
        */

        this.fitness = fitness;
    }

    get fitness() {
        return this.fitness;
    }

    set fitness(fitness) {
        if(fitness == null || fitness == undefined) throw "Fitness is invalid" 
        this.fitness = {...this.fitness, ...fitness};
    }

    /**
     * Cross the network of this agent with that of another agent.
     * @param  {EvolvingNetworkAgent} agent The agent to cross genes with
     * @return {Array}      The flattened network generated by crossing the agents' genes
     */
    cross(agent) {
        return Cross.random(agent);
    }

    /**
     * Generate a mutated network from this agent's current network.
     * @return {Array}      The flattened network generated by the mutation algorithm.
     */
    mutate() {
        return Mutate.random(agent);
    }

    getFlattened() {
        return this.network.flatten();
    }

    setFlattened(flattenedNetwork) {
        this.network.setFlattened(flattenedNetwork);
    }
}

export { EvolvingNetworkAgent };